<?php
$countryCollection = $block->getCountries();
?>
<form class="form-address-edit" data-mage-init='{"validation": {}}' action="<?= $this->getUrl('interview/index/requestorder'); ?>" method="post" id="customer-order">
    <fieldset class="fieldset">
        <legend class="legend"><span>Customer Information</span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__("Name")) ?></span></label>
            <div class="control">
                <input type="text" id="name" name="name" value="" title="<?= $block->escapeHtml(__("Name")) ?>" class="input-text" data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
            </div>
        </div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__("Email")) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="" title="<?= $block->escapeHtml(__("Email")) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field address required">
            <label for="address" class="label">
                <span><?= $block->escapeHtml(__("Address")) ?></span>
            </label>
            <div class="control">
                <input type="text" name="address" value="" title="<?= $block->escapeHtml(__("Address")) ?>" id="address" class="input-text" data-validate="{required:true}">
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__("City")) ?></span></label>
            <div class="control">
                <input type="text" name="city" value="" title="<?= $block->escapeHtml(__("City")) ?>" class="input-text" id="city" data-validate="{required:true}">
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span> <?= $block->escapeHtml(__("Zip/Postal Code")) ?></span>
            </label>
            <div class="control">
                <input type="text" name="postcode" value="" title="<?= $block->escapeHtml(__("Zip/Postal Code")) ?>" id="zip" class="input-text validate-zip-international" data-validate="{required:true, 'validate-zip-international':true}">
            </div>
        </div>
        <div class="field state required">
            <label class="label" for="state"><span><?= $block->escapeHtml(__("State")) ?></span></label>
            <div class="control">
                <input type="text" name="state" value="" title="<?= $block->escapeHtml(__("State")) ?>" class="input-text" id="state" data-validate="{required:true}">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__("Country")) ?></span></label>
            <div class="control">
                <select name="country" id="country" class="required-entry" title="<?= $block->escapeHtml(__("Country")) ?>" data-validate="{'validate-select':true}" >
                    <option value=""> Please select a Country</option>
                    <?php
                    foreach ($countryCollection as $country) :
                        if ($country['value']) {
                            ?>
                            <option value="<?= $country['label']; ?>"><?= $country['label']; ?></option>
                            <?php
                        }
                    endforeach;
                    ?>
                </select>   
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__("Product Info")) ?></span></legend><br>
        <div class="field product required">
            <label for="product_1" class="label">
                <span><?= $block->escapeHtml(__("Product Info")) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="product[]"
                       value=""
                       title="<?= $block->escapeHtml(__("Product Info")) ?>"
                       id="product_1"
                       class="input-text" placeholder="Enter Name/SKU of the Product" data-validate="{required:true}" />
                <div class="nested">
                    <?php for ($_i = 1; $_i < 3; $_i++) : ?>
                        <div class="field additional">
                            <label class="label" for="product_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Product Info %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="product[]"
                                       value=""
                                       title="<?= $block->escapeHtmlAttr(__('Product Info %1', $_i + 1)) ?>"
                                       id="product_<?= /* @noEscape */ $_i + 1 ?>"
                                       class="input-text" placeholder="Enter Name/SKU of the Product">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-order" title="<?= $block->escapeHtml(__("Request Order")) ?>">
                <span><?= $block->escapeHtml(__("Request Order")) ?></span>
            </button>
        </div>
    </div>
</form>



